PlainTexts = \
    ["Actions speak louder than words.",
     "The early bird catches the worm.",
     "Where there's smoke, there's fire.",
     "Don't count your chickens before they hatch.",
     "You can't have your cake and eat it too.",
     "When in Rome, do as the Romans do.",
     "All's fair in love and war.",
     "There's no smoke without fire.",
     "The proof of the pudding is in the eating.",
     "Don't bite the hand that feeds you.",
     "A picture is worth a thousand words.",
     "All that glitters is not gold.",
     "Every cloud has a silver lining.",
     "A watched pot never boils.",
     "Don't put all your eggs in one basket.",
     "Birds of a feather flock together.",
     "The grass is always greener on the other side.",
     "When the going gets tough, the tough get going.",
     "You can't make an omelette without breaking eggs.",
     "All is fair in love and war.",
     "The road to hell is paved with good intentions.",
     "Hindsight is 20/20.",
     "What goes around, comes around.",
     "Don't judge a book by its cover.",
     "Rome wasn't built in a day.",
     "Every dog has its day.",
     "When in doubt, do nothing.",
     "Beggars can't be choosers.",
     "Beauty is in the eye of the beholder.",
     "Necessity is the mother of invention.",
     "The best things in life are free.",
     "Time heals all wounds.",
     "Better late than never.",
     "Money can't buy happiness.",
     "Great minds think alike.",
     "Where there is a will, there is a way.",
     "It's a piece of cake.",
     "The ball is in your court.",
     "You can't judge a fish by its ability to climb a tree.",
     "Don't throw in the towel.",
     "The show must go on.",
     "Two wrongs don't make a right.",
     "The apple doesn't fall far from the tree.",
     "A penny for your thoughts.",
     "No news is good news.",
     "You're a snake in the grass.",
     "There's method to my madness.",
     "A rolling stone gathers no moss.",
     "Ignorance is bliss.",
     "A problem shared is a problem halved.",
     "The best of both worlds.",
     "A stitch in time saves nine.",
     "The more, the merrier.",
     "There's no place like home.",
     "Laughter is the best medicine.",
     "You can't always get what you want.",
     "You're a snake oil salesman.",
     "If the shoe fits, wear it.",
     "The proof is in the pudding.",
     "You can't unring a bell.",
     "A watched clock never moves.",
     "An ounce of prevention is worth a pound of cure.",
     "The pot calling the kettle black.",
     "The end justifies the means.",
     "A bird in the hand is worth two in the bush.",
     "You cry over spilt milk.",
     "All work and no play makes Jack a dull boy! #123",
     "When life gives you lemons, make lemonade! $%^&",
     "What doesn't kill you makes you stronger! 4567",
     "The pen is mightier than the sword! @!$^",
     "Actions speak louder than words! 1, 2, 3, GO!",
     "Fortune favors the bold! #Lucky7",
     "Don't count your chickens before they hatch! *56",
     "When the going gets tough, the tough get going! XYZ",
     "All is fair in love and war! @#WarZone",
     "You can't always get what you want, but you can try! 123!"
     ]
